name = "WrappedViz"
uuid = "51f01b71-94a9-4fc1-b1a6-58ee26ee16e2"
version = "0.0.1"
authors = ["Garance MalnoÃ« <106530489+malnoe@users.noreply.github.com>"]

[deps]
Bonito = "824d6782-a2ef-11e9-3a09-e5662e0c26f8"
BonitoBook = "b416d416-7a6e-4336-8c1a-1f8a8cd59518"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
WGLMakie = "276b4fcb-3e11-5398-bf8b-a0c2d153d008"

[sources]
BonitoBook = {rev = "main", url = "https://github.com/SimonDanisch/BonitoBook.jl/"}

[compat]
Bonito = "4.1.11"
BonitoBook = "0.2.0"
JSON = "1.3.0"
Makie = "0.24.7"
WGLMakie = "0.13.7"
julia = "1.10"
