name = "WrappedViz"
uuid = "51f01b71-94a9-4fc1-b1a6-58ee26ee16e2"
version = "0.0.1"
authors = ["Garance MalnoÃ« <106530489+malnoe@users.noreply.github.com>"]

[deps]
Bonito = "824d6782-a2ef-11e9-3a09-e5662e0c26f8"
BonitoBook = "b416d416-7a6e-4336-8c1a-1f8a8cd59518"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Gtk = "4c0ca9eb-093a-5379-98c5-f87ac0bbbf44"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
VegaLite = "112f6efa-9a02-5b7d-90c0-432ed331239a"
WGLMakie = "276b4fcb-3e11-5398-bf8b-a0c2d153d008"

[sources]
BonitoBook = {rev = "main", url = "https://github.com/SimonDanisch/BonitoBook.jl/"}

[compat]
Bonito = "4.1.11"
BonitoBook = "0.2.0"
DataFrames = "1.8.1"
Dates = "1.11.0"
Gtk = "1.3.1"
JSON3 = "1.14.3"
Makie = "0.24.7"
VegaLite = "3.3.0"
WGLMakie = "0.13.7"
julia = "1.10"
